name: sample-python
features:
    - buildpack-stack=ubuntu-18
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-python
  name: sample-python
